### ISSUE TITLE
Change satoshis to duffs

### ISSUE THREAD

**Issue by Alex-Werner** [dashevo/insight-api#12]
1 satoshi = 1 duff
2+ satoshi = 2+ duffs

This kind of changes are breaking changes. 
We could do that, but we had to carefully think of it. 
We have partners using it, most of them like Insight because compatibility accross multiple codebase. 
I expect them to only keep the same logic and just change the URI. 
Therefore it's not hard for them to implement. 

I think that in order to make this change in insight, we have to wait a little bit more that it became justified for them to apply that change.

**Comment by nmarley** [comment]
This kind of change is merely cosmetic and causes a larger diff when comparing to the upstream. Whether "satoshis" or "duffs", the meaning is still the same.

I don't believe we should implement this for this reason and those stated above by Alex.
