### ISSUE TITLE
voteraw api?

### ISSUE THREAD

**Issue by KamuelaFranco** [dashevo/insight-api#26]
@coolaj86, due to a repository migration, this is a copy of your issue from 13 Jan 2018:

Are there Dash-specific APIs? Like voteraw, masternode, etc?
I don't see documentation for those sorts of things.

Previous discussion:
@quangogster 22 Jan 2018:
https://dashpay.atlassian.net/wiki/spaces/DOC/pages/131924073/RPC+commands

**Comment by quangogster** [comment]
hey @KamuelaFranco this repo may-be helpful to you.  Though, it is for Syscoin but should be very similar to Dash 

https://github.com/quangogster/voteraw-signature

**Comment by nmarley** [comment]
Closed in parent repo
