### ISSUE TITLE
Coinbase addresses from some blocks not logged

### ISSUE THREAD

**Issue by KamuelaFranco** [dashevo/insight-api#28]
@bigreddmachine, due to a repository migration, this is a copy of your issue from 4 Mar 2017:

I am working on some things using the bitcore and insight APIs and have set up insight-ui-dash, insight-api-dash, and bitcore-node-dash in an Ubuntu virtual machine on my laptop so that I don't abuse the explorer here: https://insight.dash.siampm.com/Everything seems to have gone fine on install and the explorer ui and api both seem to be working nicely. However, as I've been building out methods, I encountered an issue that I can't resolve.If I query the API for coinbase address histories, many addresses do not appear to have been indexed. This does not seem to be an issue for addresses with more than 1 block mined, such as those controlled by pools. The block explorer mentioned about on siampm.com does not seem to have this issue, so I was wondering if there is some kind of flag I need to tweak or patch to apply to fix my issue.

**Comment by nmarley** [comment]
Closed in parent repo
